### PR TITLE
Features/012 Add travis configuration

### PR DESCRIPTION
**Pull request by geokala**
#12

``` gherkin
Given that I am using Travis
When I try to run tests with Travis
Then I want it to be configured correctly
```

### CODE REVIEW

**Comment by alistair-broomhead** [comment]
Could not open requirements file: [Errno 2] No such file or directory:
'dev_requirements.txt'

**Comment by geokala** [comment]
Yeah, had to base it off the test improvements bit as the requirements file and the actual test runner weren't in the develop branch yet.

**Comment by geokala** [comment]
There, build passes with that.

(just annoying that we're still in the bootstrapping stage so there are a bunch of essentially cross-dependencies)

**Comment by alistair-broomhead** [comment]
Could you rebase and squash this into a single commit on top of develop? Looks good but there's a lot of noise in this PR

**Comment by alistair-broomhead** [comment]
Also you don't need to close and reopen pull requests to change the commits included, just force push over the source branch and it'll update the pull request. The only reason to recreate a pull request is to change the destination branch.

**Comment by geokala** [comment]
True, but I really don't like using the '--force' flag... I find it somewhat distasteful that it even exists.

I can't squash all of this into a single PR on top of develop as it's based on the other two features as well- but the commits should shrink down to just three once those PRs are merged, and I can squash them into one once the others are merged.

**Comment by alistair-broomhead** [comment]
Mind if I take a look at this later?

**Comment by geokala** [comment]
No worries- just post a comment when you get a chance.

**Comment by alistair-broomhead** [comment]
I might have a simpler approach, it wouldn't include flake8, but that can be in the test improvements ticket

**Comment by geokala** [comment]
I think keeping flake8 in would be good. Of course, we can always have the travis config run multiple different things anyway so that's not an issue.

What were you thinking?

**Comment by alistair-broomhead** [comment]
I'm just about to create a new PR to test my idea - I was thinking of configuring the package to be tested by `python setup.py test` and have travis run that - it avoids intertwining the tests with linting, but doesn't preclude adding linting to travis - in fact I think automatic linting is a good idea

**Comment by geokala** [comment]
New PR looks good, probably a more familiar approach for most pythonistas so I've merged and will nuke this. The linting will be introduced in the test improvements.

**Comment by alistair-broomhead** [comment]
@geokala awesome - I thought we would probably need to set up `setup.py` eventually, and this way does what we want, so may as well do that work now ;)

**Pull request closed without merging**
