### PR TITLE
Features/014 Test improvements

### PR DESCRIPTION
**Pull request by geokala**
#14

Heavy rewrite needed following travis changes and feature location changes.

### CODE REVIEW

**Comment by geokala** [comment]
Note: Depends on feature location PR.

**Comment by alistair-broomhead** [comment]
Now that the rest is in develop, could you rebase this atop it?

**Comment by geokala** [comment]
Yup, going to rebase it (maybe later this evening, maybe tomorrow) and rework it to fit with the way we're doing travis on it.

**Comment by geokala** [comment]
I have a more developed form of this, will look into a separate PR for it later.

**Pull request closed without merging**
